export const options = [
  { id: "spain", label: "Spain" },
  { id: "england", label: "England" },
  { id: "germany", label: "Germany" },
  { id: "sweden", label: "Sweden" },
  { id: "japan", label: "Japan" },
  { id: "colombia", label: "Colombia" },
  { id: "nigeria", label: "Nigeria" },
  { id: "slovenia", label: "Slovenia" },
  { id: "senegal", label: "Senegal" },
  { id: "south africa", label: "South Africa" },
  { id: "bosnia and herzegovina", label: "Bosnia and Herzegovina" },
  { id: "belgium", label: "Belgium" },
  { id: "italy", label: "Italy" },
  { id: "korea dpr", label: "Korea DPR" },
  { id: "portugal", label: "Portugal" },
  { id: "cameroon", label: "Cameroon" },
  { id: "brazil", label: "Brazil" },
  { id: "usa", label: "USA" },
  { id: "korea republic", label: "Korea Republic" },
  { id: "serbia", label: "Serbia" },
  { id: "ghana", label: "Ghana" },
  { id: "argentina", label: "Argentina" },
  { id: "norway", label: "Norway" },
  { id: "ecuador", label: "Ecuador" },
  { id: "algeria", label: "Algeria" },
  { id: "netherlands", label: "Netherlands" },
  { id: "austria", label: "Austria" },
  { id: "france", label: "France" },
  { id: "turkey", label: "Turkey" },
  { id: "soviet union", label: "Soviet Union" },
  { id: "russia", label: "Russia" },
  { id: "saudi arabia", label: "Saudi Arabia" },
  { id: "switzerland", label: "Switzerland" },
  { id: "australia", label: "Australia" },
  { id: "morocco", label: "Morocco" },
  { id: "tunisia", label: "Tunisia" },
  { id: "egypt", label: "Egypt" },
  { id: "chile", label: "Chile" },
  { id: "ir iran", label: "IR Iran" },
  { id: "panama", label: "Panama" },
  { id: "china pr", label: "China PR" },
  { id: "canada", label: "Canada" },
  { id: "romania", label: "Romania" },
  { id: "bulgaria", label: "Bulgaria" },
  { id: "peru", label: "Peru" },
  { id: "republic of ireland", label: "Republic of Ireland" },
  { id: "denmark", label: "Denmark" },
  { id: "costa rica", label: "Costa Rica" },
  { id: "honduras", label: "Honduras" },
  { id: "slovakia", label: "Slovakia" },
  { id: "mexico", label: "Mexico" },
  { id: "zaire", label: "Zaire" },
  { id: "poland", label: "Poland" },
];
